### ISSUE TITLE
Build fails under Windows locally:  unresolved import `winapi::shared::winerror`

### ISSUE THREAD

**Issue by hauserx** [cameron-martin/bazel-lsp#92]
Extracted from https://github.com/cameron-martin/bazel-lsp/issues/62

For some reason was not able to build bazel-lsp on current HEAD though, running git-bisect shows this PR as culprit: https://github.com/cameron-martin/bazel-lsp/pull/69

I am getting an errors like:

```
error[E0432]: unresolved import `winapi::shared::winerror`
   --> ../rules_rust~~_crate~~~crate~crates__dirs-sys-next-0.1.2/src/lib.rs:131:9
    |
131 |     use winapi::shared::winerror;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^ no `winerror` in `shared`
    |
```

It works on CI but fails on my machine, something seems wrong here.

Adding below lines to Cargo.toml helps in my case:
```toml
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winerror", "combaseapi", "knownfolders", "shlobj", "shtypes", "winbase", "winnt", "wincon", "handleapi", "consoleapi" ] }
```

Bisect on rules_rust points to this PR as one that changed behavior here: https://github.com/bazelbuild/rules_rust/pull/3034
